module.exports = require("./build/default/opencl");

module.exports.CL_SUCCESS = 0;
module.exports.CL_DEVICE_NOT_FOUND = -1;
module.exports.CL_DEVICE_NOT_AVAILABLE = -2;
module.exports.CL_COMPILER_NOT_AVAILABLE = -3;
module.exports.CL_MEM_OBJECT_ALLOCATION_FAILURE = -4;
module.exports.CL_OUT_OF_RESOURCES = -5;
module.exports.CL_OUT_OF_HOST_MEMORY = -6;
module.exports.CL_PROFILING_INFO_NOT_AVAILABLE = -7;
module.exports.CL_MEM_COPY_OVERLAP = -8;
module.exports.CL_IMAGE_FORMAT_MISMATCH = -9;
module.exports.CL_IMAGE_FORMAT_NOT_SUPPORTED = -10;
module.exports.CL_BUILD_PROGRAM_FAILURE = -11;
module.exports.CL_MAP_FAILURE = -12;
module.exports.CL_MISALIGNED_SUB_BUFFER_OFFSET = -13;
module.exports.CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST = -14;
module.exports.CL_INVALID_VALUE = -30;
module.exports.CL_INVALID_DEVICE_TYPE = -31;
module.exports.CL_INVALID_PLATFORM = -32;
module.exports.CL_INVALID_DEVICE = -33;
module.exports.CL_INVALID_CONTEXT = -34;
module.exports.CL_INVALID_QUEUE_PROPERTIES = -35;
module.exports.CL_INVALID_COMMAND_QUEUE = -36;
module.exports.CL_INVALID_HOST_PTR = -37;
module.exports.CL_INVALID_MEM_OBJECT = -38;
module.exports.CL_INVALID_IMAGE_FORMAT_DESCRIPTOR = -39;
module.exports.CL_INVALID_IMAGE_SIZE = -40;
module.exports.CL_INVALID_SAMPLER = -41;
module.exports.CL_INVALID_BINARY = -42;
module.exports.CL_INVALID_BUILD_OPTIONS = -43;
module.exports.CL_INVALID_PROGRAM = -44;
module.exports.CL_INVALID_PROGRAM_EXECUTABLE = -45;
module.exports.CL_INVALID_KERNEL_NAME = -46;
module.exports.CL_INVALID_KERNEL_DEFINITION = -47;
module.exports.CL_INVALID_KERNEL = -48;
module.exports.CL_INVALID_ARG_INDEX = -49;
module.exports.CL_INVALID_ARG_VALUE = -50;
module.exports.CL_INVALID_ARG_SIZE = -51;
module.exports.CL_INVALID_KERNEL_ARGS = -52;
module.exports.CL_INVALID_WORK_DIMENSION = -53;
module.exports.CL_INVALID_WORK_GROUP_SIZE = -54;
module.exports.CL_INVALID_WORK_ITEM_SIZE = -55;
module.exports.CL_INVALID_GLOBAL_OFFSET = -56;
module.exports.CL_INVALID_EVENT_WAIT_LIST = -57;
module.exports.CL_INVALID_EVENT = -58;
module.exports.CL_INVALID_OPERATION = -59;
module.exports.CL_INVALID_GL_OBJECT = -60;
module.exports.CL_INVALID_BUFFER_SIZE = -61;
module.exports.CL_INVALID_MIP_LEVEL = -62;
module.exports.CL_INVALID_GLOBAL_WORK_SIZE = -63;
module.exports.CL_INVALID_PROPERTY = -64;
module.exports.CL_VERSION_1_0 = 1;
module.exports.CL_VERSION_1_1 = 1;
module.exports.CL_FALSE = 0;
module.exports.CL_TRUE = 1;
module.exports.CL_PLATFORM_PROFILE = 0x0900;
module.exports.CL_PLATFORM_VERSION = 0x0901;
module.exports.CL_PLATFORM_NAME = 0x0902;
module.exports.CL_PLATFORM_VENDOR = 0x0903;
module.exports.CL_PLATFORM_EXTENSIONS = 0x0904;
module.exports.CL_DEVICE_TYPE_DEFAULT = (1<<0);
module.exports.CL_DEVICE_TYPE_CPU = (1<<1);
module.exports.CL_DEVICE_TYPE_GPU = (1<<2);
module.exports.CL_DEVICE_TYPE_ACCELERATOR = (1<<3);
module.exports.CL_DEVICE_TYPE_ALL = 0xFFFFFFFF;
module.exports.CL_DEVICE_TYPE = 0x1000;
module.exports.CL_DEVICE_VENDOR_ID = 0x1001;
module.exports.CL_DEVICE_MAX_COMPUTE_UNITS = 0x1002;
module.exports.CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS = 0x1003;
module.exports.CL_DEVICE_MAX_WORK_GROUP_SIZE = 0x1004;
module.exports.CL_DEVICE_MAX_WORK_ITEM_SIZES = 0x1005;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR = 0x1006;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT = 0x1007;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT = 0x1008;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG = 0x1009;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT = 0x100A;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE = 0x100B;
module.exports.CL_DEVICE_MAX_CLOCK_FREQUENCY = 0x100C;
module.exports.CL_DEVICE_ADDRESS_BITS = 0x100D;
module.exports.CL_DEVICE_MAX_READ_IMAGE_ARGS = 0x100E;
module.exports.CL_DEVICE_MAX_WRITE_IMAGE_ARGS = 0x100F;
module.exports.CL_DEVICE_MAX_MEM_ALLOC_SIZE = 0x1010;
module.exports.CL_DEVICE_IMAGE2D_MAX_WIDTH = 0x1011;
module.exports.CL_DEVICE_IMAGE2D_MAX_HEIGHT = 0x1012;
module.exports.CL_DEVICE_IMAGE3D_MAX_WIDTH = 0x1013;
module.exports.CL_DEVICE_IMAGE3D_MAX_HEIGHT = 0x1014;
module.exports.CL_DEVICE_IMAGE3D_MAX_DEPTH = 0x1015;
module.exports.CL_DEVICE_IMAGE_SUPPORT = 0x1016;
module.exports.CL_DEVICE_MAX_PARAMETER_SIZE = 0x1017;
module.exports.CL_DEVICE_MAX_SAMPLERS = 0x1018;
module.exports.CL_DEVICE_MEM_BASE_ADDR_ALIGN = 0x1019;
module.exports.CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE = 0x101A;
module.exports.CL_DEVICE_SINGLE_FP_CONFIG = 0x101B;
module.exports.CL_DEVICE_GLOBAL_MEM_CACHE_TYPE = 0x101C;
module.exports.CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE = 0x101D;
module.exports.CL_DEVICE_GLOBAL_MEM_CACHE_SIZE = 0x101E;
module.exports.CL_DEVICE_GLOBAL_MEM_SIZE = 0x101F;
module.exports.CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE = 0x1020;
module.exports.CL_DEVICE_MAX_CONSTANT_ARGS = 0x1021;
module.exports.CL_DEVICE_LOCAL_MEM_TYPE = 0x1022;
module.exports.CL_DEVICE_LOCAL_MEM_SIZE = 0x1023;
module.exports.CL_DEVICE_ERROR_CORRECTION_SUPPORT = 0x1024;
module.exports.CL_DEVICE_PROFILING_TIMER_RESOLUTION = 0x1025;
module.exports.CL_DEVICE_ENDIAN_LITTLE = 0x1026;
module.exports.CL_DEVICE_AVAILABLE = 0x1027;
module.exports.CL_DEVICE_COMPILER_AVAILABLE = 0x1028;
module.exports.CL_DEVICE_EXECUTION_CAPABILITIES = 0x1029;
module.exports.CL_DEVICE_QUEUE_PROPERTIES = 0x102A;
module.exports.CL_DEVICE_NAME = 0x102B;
module.exports.CL_DEVICE_VENDOR = 0x102C;
module.exports.CL_DRIVER_VERSION = 0x102D;
module.exports.CL_DEVICE_PROFILE = 0x102E;
module.exports.CL_DEVICE_VERSION = 0x102F;
module.exports.CL_DEVICE_EXTENSIONS = 0x1030;
module.exports.CL_DEVICE_PLATFORM = 0x1031;
module.exports.CL_DEVICE_DOUBLE_FP_CONFIG = 0x1032;
module.exports.CL_DEVICE_HALF_FP_CONFIG = 0x1033;
module.exports.CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF = 0x1034;
module.exports.CL_DEVICE_HOST_UNIFIED_MEMORY = 0x1035;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR = 0x1036;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT = 0x1037;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_INT = 0x1038;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG = 0x1039;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT = 0x103A;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE = 0x103B;
module.exports.CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF = 0x103C;
module.exports.CL_DEVICE_OPENCL_C_VERSION = 0x103D;
module.exports.CL_FP_DENORM = (1<<0);
module.exports.CL_FP_INF_NAN = (1<<1);
module.exports.CL_FP_ROUND_TO_NEAREST = (1<<2);
module.exports.CL_FP_ROUND_TO_ZERO = (1<<3);
module.exports.CL_FP_ROUND_TO_INF = (1<<4);
module.exports.CL_FP_FMA = (1<<5);
module.exports.CL_FP_SOFT_FLOAT = (1<<6);
module.exports.CL_NONE = 0x0;
module.exports.CL_READ_ONLY_CACHE = 0x1;
module.exports.CL_READ_WRITE_CACHE = 0x2;
module.exports.CL_LOCAL = 0x1;
module.exports.CL_GLOBAL = 0x2;
module.exports.CL_EXEC_KERNEL = (1<<0);
module.exports.CL_EXEC_NATIVE_KERNEL = (1<<1);
module.exports.CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1<<0);
module.exports.CL_QUEUE_PROFILING_ENABLE = (1<<1);
module.exports.CL_CONTEXT_REFERENCE_COUNT = 0x1080;
module.exports.CL_CONTEXT_DEVICES = 0x1081;
module.exports.CL_CONTEXT_PROPERTIES = 0x1082;
module.exports.CL_CONTEXT_NUM_DEVICES = 0x1083;
module.exports.CL_CONTEXT_PLATFORM = 0x1084;
module.exports.CL_QUEUE_CONTEXT = 0x1090;
module.exports.CL_QUEUE_DEVICE = 0x1091;
module.exports.CL_QUEUE_REFERENCE_COUNT = 0x1092;
module.exports.CL_QUEUE_PROPERTIES = 0x1093;
module.exports.CL_MEM_READ_WRITE = (1<<0);
module.exports.CL_MEM_WRITE_ONLY = (1<<1);
module.exports.CL_MEM_READ_ONLY = (1<<2);
module.exports.CL_MEM_USE_HOST_PTR = (1<<3);
module.exports.CL_MEM_ALLOC_HOST_PTR = (1<<4);
module.exports.CL_MEM_COPY_HOST_PTR = (1<<5);
module.exports.CL_R = 0x10B0;
module.exports.CL_A = 0x10B1;
module.exports.CL_RG = 0x10B2;
module.exports.CL_RA = 0x10B3;
module.exports.CL_RGB = 0x10B4;
module.exports.CL_RGBA = 0x10B5;
module.exports.CL_BGRA = 0x10B6;
module.exports.CL_ARGB = 0x10B7;
module.exports.CL_INTENSITY = 0x10B8;
module.exports.CL_LUMINANCE = 0x10B9;
module.exports.CL_Rx = 0x10BA;
module.exports.CL_RGx = 0x10BB;
module.exports.CL_RGBx = 0x10BC;
module.exports.CL_SNORM_INT8 = 0x10D0;
module.exports.CL_SNORM_INT16 = 0x10D1;
module.exports.CL_UNORM_INT8 = 0x10D2;
module.exports.CL_UNORM_INT16 = 0x10D3;
module.exports.CL_UNORM_SHORT_565 = 0x10D4;
module.exports.CL_UNORM_SHORT_555 = 0x10D5;
module.exports.CL_UNORM_INT_101010 = 0x10D6;
module.exports.CL_SIGNED_INT8 = 0x10D7;
module.exports.CL_SIGNED_INT16 = 0x10D8;
module.exports.CL_SIGNED_INT32 = 0x10D9;
module.exports.CL_UNSIGNED_INT8 = 0x10DA;
module.exports.CL_UNSIGNED_INT16 = 0x10DB;
module.exports.CL_UNSIGNED_INT32 = 0x10DC;
module.exports.CL_HALF_FLOAT = 0x10DD;
module.exports.CL_FLOAT = 0x10DE;
module.exports.CL_MEM_OBJECT_BUFFER = 0x10F0;
module.exports.CL_MEM_OBJECT_IMAGE2D = 0x10F1;
module.exports.CL_MEM_OBJECT_IMAGE3D = 0x10F2;
module.exports.CL_MEM_TYPE = 0x1100;
module.exports.CL_MEM_FLAGS = 0x1101;
module.exports.CL_MEM_SIZE = 0x1102;
module.exports.CL_MEM_HOST_PTR = 0x1103;
module.exports.CL_MEM_MAP_COUNT = 0x1104;
module.exports.CL_MEM_REFERENCE_COUNT = 0x1105;
module.exports.CL_MEM_CONTEXT = 0x1106;
module.exports.CL_MEM_ASSOCIATED_MEMOBJECT = 0x1107;
module.exports.CL_MEM_OFFSET = 0x1108;
module.exports.CL_IMAGE_FORMAT = 0x1110;
module.exports.CL_IMAGE_ELEMENT_SIZE = 0x1111;
module.exports.CL_IMAGE_ROW_PITCH = 0x1112;
module.exports.CL_IMAGE_SLICE_PITCH = 0x1113;
module.exports.CL_IMAGE_WIDTH = 0x1114;
module.exports.CL_IMAGE_HEIGHT = 0x1115;
module.exports.CL_IMAGE_DEPTH = 0x1116;
module.exports.CL_ADDRESS_NONE = 0x1130;
module.exports.CL_ADDRESS_CLAMP_TO_EDGE = 0x1131;
module.exports.CL_ADDRESS_CLAMP = 0x1132;
module.exports.CL_ADDRESS_REPEAT = 0x1133;
module.exports.CL_ADDRESS_MIRRORED_REPEAT = 0x1134;
module.exports.CL_FILTER_NEAREST = 0x1140;
module.exports.CL_FILTER_LINEAR = 0x1141;
module.exports.CL_SAMPLER_REFERENCE_COUNT = 0x1150;
module.exports.CL_SAMPLER_CONTEXT = 0x1151;
module.exports.CL_SAMPLER_NORMALIZED_COORDS = 0x1152;
module.exports.CL_SAMPLER_ADDRESSING_MODE = 0x1153;
module.exports.CL_SAMPLER_FILTER_MODE = 0x1154;
module.exports.CL_MAP_READ = (1<<0);
module.exports.CL_MAP_WRITE = (1<<1);
module.exports.CL_PROGRAM_REFERENCE_COUNT = 0x1160;
module.exports.CL_PROGRAM_CONTEXT = 0x1161;
module.exports.CL_PROGRAM_NUM_DEVICES = 0x1162;
module.exports.CL_PROGRAM_DEVICES = 0x1163;
module.exports.CL_PROGRAM_SOURCE = 0x1164;
module.exports.CL_PROGRAM_BINARY_SIZES = 0x1165;
module.exports.CL_PROGRAM_BINARIES = 0x1166;
module.exports.CL_PROGRAM_BUILD_STATUS = 0x1181;
module.exports.CL_PROGRAM_BUILD_OPTIONS = 0x1182;
module.exports.CL_PROGRAM_BUILD_LOG = 0x1183;
module.exports.CL_BUILD_SUCCESS = 0;
module.exports.CL_BUILD_NONE = -1;
module.exports.CL_BUILD_ERROR = -2;
module.exports.CL_BUILD_IN_PROGRESS = -3;
module.exports.CL_KERNEL_FUNCTION_NAME = 0x1190;
module.exports.CL_KERNEL_NUM_ARGS = 0x1191;
module.exports.CL_KERNEL_REFERENCE_COUNT = 0x1192;
module.exports.CL_KERNEL_CONTEXT = 0x1193;
module.exports.CL_KERNEL_PROGRAM = 0x1194;
module.exports.CL_KERNEL_WORK_GROUP_SIZE = 0x11B0;
module.exports.CL_KERNEL_COMPILE_WORK_GROUP_SIZE = 0x11B1;
module.exports.CL_KERNEL_LOCAL_MEM_SIZE = 0x11B2;
module.exports.CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE = 0x11B3;
module.exports.CL_KERNEL_PRIVATE_MEM_SIZE = 0x11B4;
module.exports.CL_EVENT_COMMAND_QUEUE = 0x11D0;
module.exports.CL_EVENT_COMMAND_TYPE = 0x11D1;
module.exports.CL_EVENT_REFERENCE_COUNT = 0x11D2;
module.exports.CL_EVENT_COMMAND_EXECUTION_STATUS = 0x11D3;
module.exports.CL_EVENT_CONTEXT = 0x11D4;
module.exports.CL_COMMAND_NDRANGE_KERNEL = 0x11F0;
module.exports.CL_COMMAND_TASK = 0x11F1;
module.exports.CL_COMMAND_NATIVE_KERNEL = 0x11F2;
module.exports.CL_COMMAND_READ_BUFFER = 0x11F3;
module.exports.CL_COMMAND_WRITE_BUFFER = 0x11F4;
module.exports.CL_COMMAND_COPY_BUFFER = 0x11F5;
module.exports.CL_COMMAND_READ_IMAGE = 0x11F6;
module.exports.CL_COMMAND_WRITE_IMAGE = 0x11F7;
module.exports.CL_COMMAND_COPY_IMAGE = 0x11F8;
module.exports.CL_COMMAND_COPY_IMAGE_TO_BUFFER = 0x11F9;
module.exports.CL_COMMAND_COPY_BUFFER_TO_IMAGE = 0x11FA;
module.exports.CL_COMMAND_MAP_BUFFER = 0x11FB;
module.exports.CL_COMMAND_MAP_IMAGE = 0x11FC;
module.exports.CL_COMMAND_UNMAP_MEM_OBJECT = 0x11FD;
module.exports.CL_COMMAND_MARKER = 0x11FE;
module.exports.CL_COMMAND_ACQUIRE_GL_OBJECTS = 0x11FF;
module.exports.CL_COMMAND_RELEASE_GL_OBJECTS = 0x1200;
module.exports.CL_COMMAND_READ_BUFFER_RECT = 0x1201;
module.exports.CL_COMMAND_WRITE_BUFFER_RECT = 0x1202;
module.exports.CL_COMMAND_COPY_BUFFER_RECT = 0x1203;
module.exports.CL_COMMAND_USER = 0x1204;
module.exports.CL_COMPLETE = 0x0;
module.exports.CL_RUNNING = 0x1;
module.exports.CL_SUBMITTED = 0x2;
module.exports.CL_QUEUED = 0x3;
module.exports.CL_BUFFER_CREATE_TYPE_REGION = 0x1220;
module.exports.CL_PROFILING_COMMAND_QUEUED = 0x1280;
module.exports.CL_PROFILING_COMMAND_SUBMIT = 0x1281;
module.exports.CL_PROFILING_COMMAND_START = 0x1282;
module.exports.CL_PROFILING_COMMAND_END = 0x1283;

module.exports.types = {
};

var cnt = 0;
module.exports.types.UNKNOWN = cnt++;

module.exports.types.BYTE = cnt++;
module.exports.types.CHAR = cnt++;
module.exports.types.UCHAR = cnt++;
module.exports.types.SHORT = cnt++;
module.exports.types.USHORT = cnt++;

    // Basic types
module.exports.types.INT = cnt++;                        // cl_int
module.exports.types.UINT = cnt++;                       // cl_uint
module.exports.types.LONG = cnt++;                       // cl_long
module.exports.types.ULONG = cnt++;                      // cl_ulong
module.exports.types.BOOL = cnt++;                       // cl_bool = cl_uint                    //10
module.exports.types.SIZE_T = cnt++;                     // size_t
module.exports.types.HALF = cnt++;                       // cl_half
module.exports.types.FLOAT = cnt++;                      // cl_float
module.exports.types.DOUBLE = cnt++;                     // cl_double

// String types
module.exports.types.STRING = cnt++;                     // char*

    // Class types
module.exports.types.PLATFORM = cnt++;                   // cl_platform_id
module.exports.types.DEVICE = cnt++;                     // cl_device_id
module.exports.types.CONTEXT = cnt++;                    // cl_context
module.exports.types.COMMAND_QUEUE = cnt++;              // cl_command_queue
module.exports.types.MEMORY_OBJECT = cnt++;              // cl_mem                               //20
module.exports.types.MEM = module.exports.types.MEMORY_OBJECT;
module.exports.types.PROGRAM = cnt++;                    // cl_program
module.exports.types.KERNEL = cnt++;                     // cl_kernel
module.exports.types.EVENT = cnt++;                      // cl_event
module.exports.types.SAMPLER = cnt++;                    // cl_sampler

module.exports.types.IMAGE_FORMAT = cnt++;

    // Special types
module.exports.types.ADRESSING_MODE = cnt++;             // cl_addressing_mode
module.exports.types.BUILD_STATUS = cnt++;               // cl_build_status
module.exports.types.CHANNEL_ORDER = cnt++;              // cl_channel_order
module.exports.types.CHANNEL_TYPE = cnt++;               // cl_channel_type
module.exports.types.COMMAND_QUEUE_PROPERTIES = cnt++;   // cl_command_queue_properties          //30
module.exports.types.COMMAND_TYPE = cnt++;               // cl_command_type
module.exports.types.CONTEXT_PROPERTIES = cnt++;         // cl_context_properties

module.exports.types.DEVICE_EXEC_CAPABILITIES = cnt++;   // cl_device_exec_capabilities
module.exports.types.DEVICE_FP_CONFIG = cnt++;           // cl_device_fp_config
module.exports.types.DEVICE_LOCAL_MEM_TYPE = cnt++;      // cl_device_local_mem_type
module.exports.types.DEVICE_MEM_CACHE_TYPE = cnt++;      // cl_device_mem_cache_type
module.exports.types.DEVICE_TYPE = cnt++;                // cl_device_type
module.exports.types.FILTER_MODE = cnt++;                // cl_filter_mode
module.exports.types.GL_OBJECT_TYPE = cnt++;             // cl_gl_object_type
module.exports.types.MAP_FLAGS = cnt++;                  // cl_map_flags                         //40
module.exports.types.MEM_FENCE_FLAGS = cnt++;            // cl_mem_fence_flags
module.exports.types.MEM_FLAGS = cnt++;                  // cl_mem_flags
module.exports.types.MEM_OBJECT_TYPE = cnt++;            // cl_mem_object_type

    // Vector types
module.exports.types.BYTE_V = cnt++;
module.exports.types.CHAR_V = cnt++;
module.exports.types.UCHAR_V = cnt++;
module.exports.types.SHORT_V = cnt++;
module.exports.types.USHORT_V = cnt++;
module.exports.types.INT_V = cnt++;                      // cl_int*
module.exports.types.UINT_V = cnt++;                     // cl_uint*                             //50
module.exports.types.LONG_V = cnt++;                     // cl_long*
module.exports.types.ULONG_V = cnt++;                    // cl_ulong*
module.exports.types.BOOL_V = cnt++;                     // cl_bool*
module.exports.types.SIZE_T_V = cnt++;                   // size_t*
module.exports.types.HALF_V = cnt++;
module.exports.types.FLOAT_V = cnt++;
module.exports.types.DOUBLE_V = cnt++;
module.exports.types.STRING_V = cnt++;                   // char**

module.exports.types.PLATFORM_V = cnt++;
module.exports.types.DEVICE_V = cnt++;                                                           //60
module.exports.types.CONTEXT_V = cnt++;
module.exports.types.COMMAND_QUEUE_V = cnt++;
module.exports.types.MEMORY_OBJECT_V = cnt++;
module.exports.types.PROGRAM_V = cnt++;
module.exports.types.KERNEL_V = cnt++;
module.exports.types.EVENT_V = cnt++;
module.exports.types.SAMPLER_V = cnt++;

module.exports.types.LAST = cnt;
